### PR TITLE
Only build master

### PR DESCRIPTION
**Pull request by Arcanemagus**
Set Travis-CI and AppVeyor to only build the master branch (preventing duplicate builds on PRs).
Also only clone the last 10 commits.

### CODE REVIEW

**Comment by ntwb** [comment]
Awesome, this has annoyed my for quite some time, particularly AppVeyor :smirk: 

If we're going to do Git shallow clones, then setting to `1` is all that is needed rather than `10`, could you update the pull request so the clone depth is `1` please.

**Comment by Arcanemagus** [comment]
Sure, just a sec.

**Comment by Arcanemagus** [comment]
Actually, would you prefer a shallow clone? (download + extract the zip)

**Comment by ntwb** [comment]
Just changing From:
```
git:
   depth: 10
```

To:
```
git:
   depth: 1
```

That should be fine, Travis will pass that as `$ git clone --depth=1 --branch=master https://github.com/ntwb/bbPress.git ntwb/stylelint-config-wordpress` when checking out the repo in each job

**Comment by Arcanemagus** [comment]
Updated :wink:

**Comment by ntwb** [comment]
Thanks :+1: 

> This would mean the local folder isn't a git repo, but is probably faster if you don't need that.

Its still a Git repo as far as I  understand it:

> https://git-scm.com/docs/git-clone
> `--depth` <depth>
> > Create a shallow clone with a history truncated to the specified number of commits. Implies --single-branch unless --no-single-branch is given to fetch the histories near the tips of all branches.

**Comment by Arcanemagus** [comment]
I was talking about the `shallow_clone` option [here](http://www.appveyor.com/docs/appveyor-yml#file-appveyor-yml-L51). (I'm not sure if there is an equivalent option for Travis-CI.)

**Comment by ntwb** [comment]
Oh, I've kind of always treated them the same ¯\_(ツ)_/¯

See Travis CI doc [here](https://github.com/travis-ci/docs-travis-ci-com/blob/76a37b5a1e0499136fc8cd878cb74a997509d832/user/customizing-the-build.md#git-clone-depth)

**Comment by Arcanemagus** [comment]
I think in this instance AppVeyor is confusing terminology, I've always heard of setting the clone depth as a "shallow clone" myself.

**Comment by ntwb** [comment]
Thanks again :+1:

**Pull request merged**
