### PR TITLE
Add peerDependencies section to package.json and declare stylelint dependency version

### PR DESCRIPTION
**Pull request by ntwb**
See #38

### CODE REVIEW

**Comment by ntwb** [comment]
@Arcanemagus is this all you need?

**Comment by Arcanemagus** [comment]
That should work, as far as I understand it. Thanks!

**Comment by ntwb** [comment]
I'll package this up now and release `stylelint-config-wordpress` v`3.0.1` to npmjs.com.

**Comment by Arcanemagus** [comment]
Looks like it worked perfectly :wink:
https://circleci.com/gh/AtomLinter/linter-stylelint/201

**Comment by ntwb** [comment]
Cool :+1:

**Pull request merged**
